//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public long id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public System.DateTime year { get; set; }
        public string trim { get; set; }
    }
}
